interface IObjectKeys {
  [key: string]: any;
}

export interface RawCoinMarketsInterface extends IObjectKeys {
  id: string;
  symbol: string;
  name: string;
  image: any;
  current_price: number;
  market_cap: number;
  market_cap_rank: number;
  fully_diluted_valuation: number;
  total_volume: number;
  high_24h: number;
  low_24h: number;
  price_change_24h: number;
  price_change_percentage_24h: number;
  market_cap_change_24h: number;
  market_cap_change_percentage_24h: number;
  circulating_supply: number;
  total_supply: number;
  max_supply: number;
  ath: number;
  ath_change_percentage: number;
  ath_date: number;
  atl: number;
  atl_change_percentage: number;
  atl_date: string;
  roi: null | string;
  last_updated: string;
  price_change_percentage_24h_in_currency?: number;
  price_change_percentage_1h_in_currency?: number;
  price_change_percentage_7d_in_currency?: number;
  asset_platform_id: null | string;
  platforms: Record<string, string>;
  detail_platforms: Record<string, any>;
  block_time_in_minutes: number;
  hashing_algorithm: string;
  categories: string[];
  public_notice: null | string;
  additional_notices: any[];
  description: {
    en: string;
  };
  links: {
    homepage: string[];
    blockchain_site: string[];
    official_forum_url: string[];
    chat_url: string[];
    announcement_url: string[];
    twitter_screen_name: string;
    facebook_username: string;
    bitcointalk_thread_identifier: null | string;
    telegram_channel_identifier: string;
    subreddit_url: string;
    repos_url: {
      github: string[];
      bitbucket: string[];
    };
  };

  country_origin: string;
  genesis_date: string;
  sentiment_votes_up_percentage: number;
  sentiment_votes_down_percentage: number;
  ico_data: {
    ico_start_date: string;
    ico_end_date: string;
    short_desc: string;
    description: null | string;
    links: object;
    softcap_currency: string;
    hardcap_currency: string;
    total_raised_currency: string;
    softcap_amount: null | string;
    hardcap_amount: null | string;
    total_raised: null | string;
    quote_pre_sale_currency: string;
    base_pre_sale_amount: null | string;
    quote_pre_sale_amount: null | string;
    quote_public_sale_currency: string;
    base_public_sale_amount: number;
    quote_public_sale_amount: number;
    accepting_currencies: string;
    country_origin: string;
    pre_sale_start_date: number | null;
    pre_sale_end_date: null | number;
    whitelist_url: string;
    whitelist_start_date: null | string;
    whitelist_end_date: null | string;
    bounty_detail_url: string;
    amount_for_sale: null | string;
    kyc_required: boolean;
    whitelist_available: null | string;
    pre_sale_available: null | string;
    pre_sale_ended: boolean;
  };
  market_data: {
    current_price: Record<string, number>;
    total_value_locked: string | null;
    mcap_to_tvl_ratio: string | null;
    fdv_to_tvl_ratio: string | null;
    roi: string | null;
    ath: Record<string, number>;
    ath_change_percentage: Record<string, number>;
    ath_date: Record<string, number>;
    atl: Record<string, number>;
    atl_change_percentage: Record<string, number>;
    atl_date: Record<string, string>;
    market_cap: Record<string, number>;
    market_cap_rank: number;
    fully_diluted_valuation: Record<string, number>;
    total_volume: Record<string, number>;
    high_24h: Record<string, number>;
    low_24h: Record<string, number>;
    price_change_24h: number;
    price_change_percentage_24h: number;
    price_change_percentage_7d: number;
    price_change_percentage_14d: number;
    price_change_percentage_30d: number;
    price_change_percentage_60d: number;
    price_change_percentage_200d: number;
    price_change_percentage_1y: number;
    market_cap_change_24h: number;
    market_cap_change_percentage_24h: number;
    price_change_24h_in_currency: Record<string, number>;
    price_change_percentage_1h_in_currency: Record<string, number>;
    price_change_percentage_24h_in_currency: Record<string, number>;
    price_change_percentage_7d_in_currency: Record<string, number>;
    price_change_percentage_14d_in_currency: Record<string, number>;
    price_change_percentage_30d_in_currency: Record<string, number>;
    price_change_percentage_60d_in_currency: Record<string, number>;
    price_change_percentage_200d_in_currency: Record<string, number>;
    price_change_percentage_1y_in_currency: Record<string, number>;
    market_cap_change_24h_in_currency: Record<string, number>;
    market_cap_change_percentage_24h_in_currency: Record<string, number>;
    total_supply: number;
    max_supply: number;
    circulating_supply: number;
    last_updated: string;
  };
  coingecko_rank: number;
  coingecko_score: number;
  developer_score: number;
  community_score: number;
  liquidity_score: number;
  public_interest_score: number;
  public_interest_stats: {
    alexa_rank: number;
    bing_matches: null | string;
  };
  status_updates: any[];
}

export interface RawGlobalMarketInterface {
  data: {
    active_cryptocurrencies: number;
    upcoming_icos: number;
    ongoing_icos: number;
    ended_icos: number;
    markets: number;
    total_market_cap: {
      btc: number;
      eth: number;
      ltc: number;
      bch: number;
      bnb: number;
      eos: number;
      xrp: number;
      xlm: number;
      link: number;
      dot: number;
      yfi: number;
      usd: number;
      aed: number;
      ars: number;
      aud: number;
      bdt: number;
      bhd: number;
      bmd: number;
      brl: number;
      cad: number;
      chf: number;
      clp: number;
      cny: number;
      czk: number;
      dkk: number;
      eur: number;
      gbp: number;
      hkd: number;
      huf: number;
      idr: number;
      ils: number;
      inr: number;
      jpy: number;
      krw: number;
      kwd: number;
      lkr: number;
      mmk: number;
      mxn: number;
      myr: number;
      ngn: number;
      nok: number;
      nzd: number;
      php: number;
      pkr: number;
      pln: number;
      rub: number;
      sar: number;
      sek: number;
      sgd: number;
      thb: number;
      try: number;
      twd: number;
      uah: number;
      vef: number;
      vnd: number;
      zar: number;
      xdr: number;
      xag: number;
      xau: number;
      bits: number;
      sats: number;
    };
    total_volume: {
      btc: number;
      eth: number;
      ltc: number;
      bch: number;
      bnb: number;
      eos: number;
      xrp: number;
      xlm: number;
      link: number;
      dot: number;
      yfi: number;
      usd: number;
      aed: number;
      ars: number;
      aud: number;
      bdt: number;
      bhd: number;
      bmd: number;
      brl: number;
      cad: number;
      chf: number;
      clp: number;
      cny: number;
      czk: number;
      dkk: number;
      eur: number;
      gbp: number;
      hkd: number;
      huf: number;
      idr: number;
      ils: number;
      inr: number;
      jpy: number;
      krw: number;
      kwd: number;
      lkr: number;
      mmk: number;
      mxn: number;
      myr: number;
      ngn: number;
      nok: number;
      nzd: number;
      php: number;
      pkr: number;
      pln: number;
      rub: number;
      sar: number;
      sek: number;
      sgd: number;
      thb: number;
      try: number;
      twd: number;
      uah: number;
      vef: number;
      vnd: number;
      zar: number;
      xdr: number;
      xag: number;
      xau: number;
      bits: number;
      sats: number;
    };
    market_cap_percentage: {
      btc: number;
      eth: number;
      usdt: number;
      bnb: number;
      usdc: number;
      xrp: number;
      ada: number;
      okb: number;
      doge: number;
      matic: number;
    };
    market_cap_change_percentage_24h_usd: number;
    updated_at: number;
  };
}
